local deftest = require "deftest.deftest"

local tests = {
	-- Eva module
	require("test.tests.eva_offers"),
	require("test.tests.eva_timers"),
	require("test.tests.eva_daily"),
	require("test.tests.eva_festivals"),
	require("test.tests.eva_quests"),
	require("test.tests.eva_grids"),
	require("test.tests.eva_push"),
	require("test.tests.eva_invoices"),
	require("test.tests.eva_iaps"),
	require("test.tests.eva_callbacks"),
	require("test.tests.eva_rating"),
	require("test.tests.eva_storage"),
	require("test.tests.eva_lang"),
	require("test.tests.eva_token"),
	require("test.tests.eva_tokens"),
	require("test.tests.eva_containers"),
	require("test.tests.eva_trucks"),
	require("test.tests.eva_migrations"),
	require("test.tests.eva_skills"),
	require("test.tests.eva_promocode"),
	require("test.tests.eva_ads"),

	-- New tests, unimplemented
	require("test.tests.eva_events"),
	require("test.tests.eva_saver"),
	require("test.tests.eva_rate"),
	require("test.tests.eva_window"),

	-- Libs
	require("test.tests.smart_value"),
	require("test.tests.iso_time"),
	require("test.tests.eva_luax"),
}


function init(self)
	print('[DefTest]: Init of DefTest')
	for i = 1, #tests do
		deftest.add(tests[i])
	end

	local is_report = (sys.get_config("test.report") == "1")
	deftest.run({ coverage = { enabled = is_report } })
end
