language: java

jdk:
  - oraclejdk11

env:
  global:
    - DEFOLD_AUTH=12345
    - DEFOLD_USER=some@gmail.com
    - DEFOLD_BOOSTRAP_COLLECTION=/test/test.collectionc

script:
  - "./.travis/run.sh"

after_success:
  - bash <(curl -s https://codecov.io/bash)