local eva = require("eva.eva")
local window_settings = require("main.window_settings")
local eva_migrations = require("main.test_migrations")

function init(self)
	eva.init(nil, {
		migrations = eva_migrations,
		window_settings = window_settings
	})

	msg.post(".", "late_init")
end


function on_message(self, message_id, message, sender)
	if message_id == hash("late_init") then
		eva.window.show_scene("scene_main")
	end
end