name: CI

on: [push]

jobs:
    build_and_run:
        name: Build and run
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
          - uses: actions/setup-java@v1
            with:
                java-version: '13'
          - name: Run.sh
            run: ./.travis/run.sh